#!/usr/bin/env python3
"""Build the contract. Write or check the pinned proof input."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
subprocess.run(["forge", "build", "--skip", "test"], cwd=ROOT, check=True)
artifact = json.loads((ROOT / "out/Rollup.sol/Rollup.json").read_text())
layout = json.loads(subprocess.check_output(
    ["forge", "inspect", "Rollup", "storage-layout", "--json"], cwd=ROOT, text=True))
creation = artifact["bytecode"]["object"].removeprefix("0x")
runtime = artifact["deployedBytecode"]["object"].removeprefix("0x")
if not runtime or not creation.endswith(runtime):
    raise SystemExit("Creation code must end with the runtime code.")
creation_prefix = creation[:-len(runtime)]


def lean_array(name, value):
    values = list(bytes.fromhex(value))
    rows = ["    " + ", ".join(map(str, values[i:i + 24])) for i in range(0, len(values), 24)]
    return f"def {name} : ByteArray :=\n  ⟨#[\n" + ",\n".join(rows) + "\n  ]⟩\n"


lean = ("-- Generated by scripts/artifacts.py. Do not edit.\n"
        "namespace Rollup.EVM\n\n" + lean_array("creationPrefix", creation_prefix)
        + "\n" + lean_array("runtimeBytecode", runtime)
        + "\ndef creationBytecode : ByteArray := creationPrefix ++ runtimeBytecode\n"
        + "\nend Rollup.EVM\n")
metadata = artifact["metadata"]
if isinstance(metadata, str):
    metadata = json.loads(metadata)
manifest = {
    "compiler": metadata["compiler"]["version"],
    "settings": metadata["settings"],
    "source_sha256": hashlib.sha256((ROOT / "contract/Rollup.sol").read_bytes()).hexdigest(),
    "creation_sha256": hashlib.sha256(bytes.fromhex(creation)).hexdigest(),
    "runtime_sha256": hashlib.sha256(bytes.fromhex(runtime)).hexdigest(),
    "creation_bytes": len(creation) // 2,
    "runtime_bytes": len(runtime) // 2,
    "selectors": artifact["methodIdentifiers"],
    "storage": [{k: row[k] for k in ["label", "offset", "slot", "type"]} for row in layout["storage"]],
    "storage_types": layout["types"],
}
outputs = {
    "contract/creation.hex": creation + "\n",
    "contract/runtime.hex": runtime + "\n",
    "contract/build.json": json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    "semantics/Bytecode.lean": lean,
}
for path, content in outputs.items():
    target = ROOT / path
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit(f"Proof input differs: {path}. Run scripts/artifacts.py, then review the proofs.")
    else:
        target.write_text(content)
print("Proof inputs match." if args.check else "Proof inputs written.")
