#!/usr/bin/env python3
"""Generate a candidate path certificate. Lean must check the result."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CODE = bytes.fromhex((ROOT / "contract/runtime.hex").read_text().strip().removeprefix("0x"))
MASK = (1 << 256) - 1
ANY, NONZERO = "?", "!"


def signed(value):
    return value if value < 1 << 255 else value - (1 << 256)


def successors(cursor):
    pc, stored = cursor
    stack = list(stored)
    op = CODE[pc]
    following = pc + 1
    if op in (0x00, 0xF3, 0xFD, 0xFE):
        return []
    if op == 0x5F:
        stack.insert(0, 0)
    elif 0x60 <= op <= 0x7F:
        width = op - 0x5F
        stack.insert(0, int.from_bytes(CODE[following:following + width], "big"))
        following += width
    elif 0x80 <= op <= 0x8F:
        stack.insert(0, stack[op - 0x80])
    elif 0x90 <= op <= 0x9F:
        index = op - 0x8F
        stack[0], stack[index] = stack[index], stack[0]
    elif op in (0x01, 0x03, 0x10, 0x11, 0x12, 0x14, 0x16, 0x1B, 0x1C):
        left, right = stack.pop(0), stack.pop(0)
        if isinstance(left, int) and isinstance(right, int):
            operations = {
                0x01: lambda: left + right,
                0x03: lambda: left - right,
                0x10: lambda: int(left < right),
                0x11: lambda: int(left > right),
                0x12: lambda: int(signed(left) < signed(right)),
                0x14: lambda: int(left == right),
                0x16: lambda: left & right,
                0x1B: lambda: right << left if left < 256 else 0,
                0x1C: lambda: right >> left if left < 256 else 0,
            }
            stack.insert(0, operations[op]() & MASK)
        else:
            stack.insert(0, ANY)
    elif op == 0x15:
        value = stack.pop(0)
        stack.insert(0, int(value == 0) if isinstance(value, int) else 0 if value == NONZERO else ANY)
    elif op in (0x34, 0x36):
        stack.insert(0, ANY)
    elif op in (0x35, 0x51):
        stack[0] = ANY
    elif op == 0x20:
        stack.pop(0)
        stack[0] = ANY
    elif op == 0x54:
        stack[0] = NONZERO if stack[0] == 6 else ANY
    elif op in (0x50, 0x52):
        for _ in range(1 if op == 0x50 else 2):
            stack.pop(0)
    elif op in (0x56, 0x57):
        destination = stack.pop(0)
        if not isinstance(destination, int) or CODE[destination] != 0x5B:
            raise ValueError(f"Unresolved or invalid jump at {pc}")
        taken = (destination, tuple(stack))
        if op == 0x56:
            return [taken]
        condition = stack.pop(0)
        taken = (destination, tuple(stack))
        fallthrough = (following, tuple(stack))
        if isinstance(condition, int):
            return [fallthrough if condition == 0 else taken]
        return [taken] if condition == NONZERO else [taken, fallthrough]
    elif op != 0x5B:
        raise ValueError(f"Unsupported opcode {op:02x} at {pc}")
    return [(following, tuple(stack))]


def lean_word(value):
    if value == ANY:
        return ".any"
    if value == NONZERO:
        return ".nonzero"
    return f".exact ⟨{value}⟩"


def main():
    states = [(0, ())]
    seen = set(states)
    index = 0
    while index < len(states):
        for following in successors(states[index]):
            if following not in seen:
                seen.add(following)
                states.append(following)
        index += 1
    rows = [f"  ⟨⟨{pc}⟩, [{', '.join(map(lean_word, stack))}]⟩" for pc, stack in states]
    header = """import proofs.support.AbstractCursor
import semantics.Bytecode

open Ethereum Ethereum.EVM

namespace Rollup.EVM

/-- Candidate locked-state paths. Generated by scripts/locked_paths.py. -/
def lockedPaths : Array AbstractCursor := #[
"""
    output = header + ",\n".join(rows) + "\n]\n\nend Rollup.EVM\n"
    (ROOT / "proofs/generated/LockedPaths.lean").write_text(output)
    print(f"Generated {len(states)} candidate states at {len({pc for pc, _ in states})} counters.")


if __name__ == "__main__":
    main()
